In [17]:
import pandas as pd
import numpy as np
import duckdb

In [18]:
DATA_PATH = '~/projects/bookrank/app/data/goodreads_joined.parquet'

In [19]:
sql = f"""
SELECT *
FROM READ_PARQUET('{DATA_PATH}') 
LIMIT 100
"""
df = duckdb.sql(sql).to_df()

In [20]:
df

,work_id,best_book_id,ratings_count,avg_rating,title,description,image_url,author_name,ordered_id
0,2792775,2767052,5066596.0,4.339298,"The Hunger Games (The Hunger Games, #1)",Winning will make you famous.\nLosing means ce...,https://images.gr-assets.com/books/1447303603m...,Suzanne Collins,1
1,4640799,3,4972886.0,4.446229,Harry Potter and the Sorcerer's Stone (Harry P...,Harry Potter's life is miserable. His parents ...,https://images.gr-assets.com/books/1474154022m...,J.K. Rowling,2
2,3212258,41865,3992661.0,3.572623,"Twilight (Twilight, #1)",About three things I was absolutely positive.\...,https://images.gr-assets.com/books/1361039443m...,Stephenie Meyer,3
3,3275794,2657,3402363.0,4.256532,To Kill a Mockingbird,The unforgettable novel of a childhood in a sl...,https://images.gr-assets.com/books/1361975680m...,Harper Lee,4
4,245494,4671,2852789.0,3.891366,The Great Gatsby,"THE GREAT GATSBY, F. Scott Fitzgerald's third ...",https://images.gr-assets.com/books/1490528560m...,F. Scott Fitzgerald,5
...,...,...,...,...,...,...,...,...,...
95,992628,21787,662378.0,4.253910,The Princess Bride,What happens when the most beautiful girl in t...,https://images.gr-assets.com/books/1327903636m...,William Goldman,96
96,3376836,6424171,661472.0,3.969471,"Jurassic Park (Jurassic Park, #1)",A billionaire has created a technique to clone...,https://images.gr-assets.com/books/1344371661m...,Michael Crichton,97
97,3020535,19543,651469.0,4.215422,Where the Wild Things Are,One night Max puts on his wolf suit and makes ...,https://images.gr-assets.com/books/1384434560m...,Maurice Sendak,98
98,3443248,3777732,645256.0,4.338952,"City of Glass (The Mortal Instruments, #3)",Also see: Alternate Cover Editions for this IS...,https://images.gr-assets.com/books/1369452339m...,Cassandra Clare,99
99,16813814,11857408,629737.0,3.866228,"Fifty Shades Darker (Fifty Shades, #2)",Daunted by the singular sexual tastes and dark...,https://images.gr-assets.com/books/1358266080m...,E.L. James,100

In [15]:
sql = f"""
SELECT
    work_id,
    title,
    author_name as author,
    description,
    image_url,
    CASE 
        WHEN RANDOM() < 0.4 THEN 'Fiction'
        WHEN RANDOM() < 0.8 THEN 'Non-Fiction' 
        ELSE 'Children'
    END as book_type,
    CASE 
        WHEN RANDOM() < 0.111 THEN 'Science Fiction'
        WHEN RANDOM() < 0.222 THEN 'Fantasy'
        WHEN RANDOM() < 0.333 THEN 'Mystery'
        WHEN RANDOM() < 0.444 THEN 'Romance'
        WHEN RANDOM() < 0.555 THEN 'Thriller'
        WHEN RANDOM() < 0.666 THEN 'Horror'
        WHEN RANDOM() < 0.777 THEN 'Historical Fiction'
        WHEN RANDOM() < 0.888 THEN 'Classics'
        ELSE 'Contemporary'
    END as genre,
    ratings_count,
    avg_rating AS average_rating
FROM READ_PARQUET('{DATA_PATH}') 
WHERE author_name IS NULL
LIMIT 100
"""
df = duckdb.sql(sql).to_df()

In [16]:
df.head()

,work_id,title,author,description,image_url,book_type,genre,ratings_count,average_rating
0,1741690,Cuando nos alcanza el ayer,None,De la solapa del libro:\nEsta obra sera lectur...,https://images.gr-assets.com/books/1314462072m...,Non-Fiction,Science Fiction,7.0,4.142857
1,19066872,Fragranfrantik,None,"""Jadi sekiranya kamu mau seperti aku, seharusn...",https://images.gr-assets.com/books/1330963783m...,Non-Fiction,Fantasy,2.0,3.500000
2,6208765,Higurashi No Naku Koro Ni Tettei Kaiseki Bukku,None,"02Nian nokomikedeDeng Chang Yi Lai , Kou komid...",https://images.gr-assets.com/books/1329305655m...,Non-Fiction,Fantasy,2.0,4.500000
3,52124320,Fueling The Fire,None,A collection of rhyming poem's with alliterati...,https://s.gr-assets.com/assets/nophoto/book/11...,Fiction,Science Fiction,1.0,5.000000

In [4]:
df.head()

,work_id,best_book_id,ratings_count,avg_rating,title,description,image_url,author_name,ordered_id
0,2792775,2767052,5066596.0,4.339298,"The Hunger Games (The Hunger Games, #1)",Winning will make you famous.\nLosing means ce...,https://images.gr-assets.com/books/1447303603m...,Suzanne Collins,1
1,4640799,3,4972886.0,4.446229,Harry Potter and the Sorcerer's Stone (Harry P...,Harry Potter's life is miserable. His parents ...,https://images.gr-assets.com/books/1474154022m...,J.K. Rowling,2
2,3212258,41865,3992661.0,3.572623,"Twilight (Twilight, #1)",About three things I was absolutely positive.\...,https://images.gr-assets.com/books/1361039443m...,Stephenie Meyer,3
3,3275794,2657,3402363.0,4.256532,To Kill a Mockingbird,The unforgettable novel of a childhood in a sl...,https://images.gr-assets.com/books/1361975680m...,Harper Lee,4
4,245494,4671,2852789.0,3.891366,The Great Gatsby,"THE GREAT GATSBY, F. Scott Fitzgerald's third ...",https://images.gr-assets.com/books/1490528560m...,F. Scott Fitzgerald,5